// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * Validates the extended navigation node form in real time.
 *
 * @module     local_extendednav/node_form
 * @copyright  2026 Didactika
 * @author     Miguel Rivas Morantes <miguelrivasmorantes@gmail.com>
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

/**
 * Inserts the requirement HTML at the correct standard position inside the label container.
 *
 * @param {HTMLElement} labelContainer The title or url label container.
 * @param {String} reqStarHTML The native requirement HTML generated by PHP.
 */
const appendRequiredIcon = (labelContainer, reqStarHTML) => {
    if (!labelContainer || labelContainer.querySelector('.req')) {
        return;
    }

    const helpIcon = labelContainer.querySelector('.btn-link, [data-region="help-link"], .text-info');
    if (helpIcon) {
        helpIcon.insertAdjacentHTML('beforebegin', reqStarHTML);
    } else {
        labelContainer.insertAdjacentHTML('beforeend', reqStarHTML);
    }
};

/**
 * Checks if the currently typed key is a core key and toggles form UI requirements.
 *
 * @param {HTMLInputElement} nodekeyInput The input node key element.
 * @param {Array} coreKeys Array of native core node keys.
 * @param {Array} customKeys Array of custom node keys.
 * @param {HTMLElement} titleLabel The title label container.
 * @param {HTMLElement} urlLabel The url label container.
 * @param {HTMLElement} coreAlertBox The core node alert box.
 * @param {HTMLElement} dupAlertBox The duplicate node alert box.
 * @param {String} reqStarHTML The native requirement HTML generated by PHP.
 */
const checkCoreKey = (nodekeyInput, coreKeys, customKeys, titleLabel, urlLabel, coreAlertBox, dupAlertBox, reqStarHTML) => {
    const current = nodekeyInput.value.trim();

    if (dupAlertBox) {
        dupAlertBox.style.display = (customKeys.indexOf(current) !== -1) ? 'block' : 'none';
    }

    if (coreKeys.indexOf(current) !== -1) {
        if (coreAlertBox) {
            coreAlertBox.style.display = 'block';
        }

        const existingTitleReq = titleLabel?.querySelector('.req');
        if (existingTitleReq) {
            existingTitleReq.remove();
        }
        const existingUrlReq = urlLabel?.querySelector('.req');
        if (existingUrlReq) {
            existingUrlReq.remove();
        }
    } else {
        if (coreAlertBox) {
            coreAlertBox.style.display = 'none';
        }

        if (reqStarHTML) {
            appendRequiredIcon(titleLabel, reqStarHTML);
            appendRequiredIcon(urlLabel, reqStarHTML);
        }
    }
};

/**
 * Initialize the node form real-time validation without jQuery.
 *
 * @param {Array} coreKeys Array of native core node keys.
 * @param {String} reqStarHTML Generated requirement HTML snippet.
 * @param {Array} customKeys Array of custom node keys.
 */
export const init = (coreKeys, reqStarHTML, customKeys) => {
    const nodekeyInput = document.querySelector('input[name="nodekey"]');
    const titleInput = document.querySelector('input[name="title"]');
    const urlInput = document.querySelector('input[name="url"]');

    if (!nodekeyInput || !titleInput || !urlInput) {
        return;
    }

    const titleLabel = titleInput.closest('.fitem')?.querySelector('.col-form-label') ||
                       titleInput.closest('.form-group')?.querySelector('.col-form-label');
    const urlLabel = urlInput.closest('.fitem')?.querySelector('.col-form-label') ||
                     urlInput.closest('.form-group')?.querySelector('.col-form-label');
    const coreAlertBox = document.getElementById('core_node_alert');
    const dupAlertBox = document.getElementById('duplicate_node_alert');

    const handler = () => {
        checkCoreKey(nodekeyInput, coreKeys, customKeys || [], titleLabel, urlLabel, coreAlertBox, dupAlertBox, reqStarHTML);
    };

    nodekeyInput.addEventListener('keyup', handler);
    nodekeyInput.addEventListener('change', handler);
    nodekeyInput.addEventListener('input', handler);

    handler();
};
